FROM openjdk:16
WORKDIR /OASIP-BE
ADD target/classicmodels-service2-0.0.1-SNAPSHOT.jar classicmodels-service2-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","classicmodels-service2-0.0.1-SNAPSHOT.jar"]