#spring:
#  main:
#    allow-circular-references: true
#
#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          oidc:
#            issuer-uri: https://intproj21.sit.kmutt.ac.th/kw3/#/Login